### ISSUE TITLE
`Stringify` trait is unsound

### ISSUE THREAD

**Issue by CodesInChaos** [zacharygolba/json-api-rs#33]
`stringify` trusts `to_bytes` to return valid UTF-8. But since `to_bytes` is public and neither the `Stringify` trait nor the `to_bytes` function are marked `unsafe`, external code can implement this trait method and violate `stringify`s assumptions.

Since `to_bytes` is safe to call, I'd mark the trait as unsafe. Alternatively you could use `from_utf8` in the default implementation of `stringify` and only use `from_utf8_unchecked` for trusted types.

**Comment by zacharygolba** [comment]
> external code can implement this trait method and violate stringifys assumptions.

You're absolutely right. This slipped through the cracks, thanks for pointing it out!

> I'd mark the trait as unsafe. Alternatively you could use from_utf8 in the default implementation of stringify and only use from_utf8_unchecked for trusted types.

Both of the options mentioned above would have been a breaking change. Since a breaking change would have been unavoidable, I decided to remove the `Stringify` trait entirely. It didn't provide much benefit over `std::string::ToString` and internal uses were becoming a bit overloaded in terms of intent.

I would love to get some feedback on this and/or know if you had any uses for `Stringify` that cannot be solved by implemented `std::fmt::Display` and calling `.to_string()`.

Thanks again for your help! 🍻
